### ISSUE TITLE
Error when launching docker container

### ISSUE THREAD

**Issue by donbalon4** [nouchka/docker-hattrick-organiser#2]
Hi, I get a permission error when I launch the app:

![imagen](https://user-images.githubusercontent.com/3063810/60763201-5cb00700-a03d-11e9-8d43-9bd63266cb9f.png)
Could you suggest me some patch?

Regards

**Comment by nouchka** [comment]
it's seems to be a write access problem for the mount directory.
In my setup, I'm on linux and my user id is 1000, so it's working fine when the directory mount to /home/user/.hattrickorganizer/ is with my uid 1000:1000.
are you on linux ? what's your uid (echo $UID) ? as a backup solution you can chmod 777 -R the directory
i'm thinking doing a script to ajust the uid

**Comment by donbalon4** [comment]
Hi, yeah, Im Ubuntu user.
my uid is 1000.
I did a little change in the docker-compose file.
I changed line 8 to:

`- ~/hrf/:/home/$USER/.hattrickorganizer/`

And it worked.
I have other question.
If you want, I can create another issue.
My question is: it is necessary to recreate the container each time?

**Comment by nouchka** [comment]
ok nice if the change make it works

you can keep the container and avoid recreating it.
